name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  linters:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Prettier Action Plugins
        uses: sebkolind/prettier_action@0.0.6
      - name: Lint Code Base
        uses: github/super-linter@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Actions Workflow Linter
        uses: cschleiden/actions-linter@v1
  metrics:
    runs-on: ubuntu-latest
    needs: linters
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.0.0
      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1.1.0
      - name: Container image scan
        uses: Azure/container-scan@v0.1